package cc.openxiot.matrix.device.loach._airconditioner._g1._heatercooler.properties;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

import cn.geekcity.xiot.spec.definition.property.*;
import cn.geekcity.xiot.spec.definition.property.data.DataFormat;
import cn.geekcity.xiot.spec.definition.urn.PropertyType;
import cn.geekcity.xiot.spec.error.IotError;
import cn.geekcity.xiot.support.codegen.vertx.typedef.controller.PropertyController;



/**
 * Property: 当前状态
 */
public class PropertyCurrentHeaterCoolerState extends PropertyController<Integer> {

    public static final int IID = 12;
    public static final String TYPE = "urn:homekit-spec:property:current-heater-cooler-state:000000b1:loach:g1:1";

    public PropertyCurrentHeaterCoolerState() {
        super(IID, new PropertyType(TYPE), new Access(false, true, true), DataFormat.UINT8);

        super.description().put("zh-CN", "当前状态");

        List<ValueDefinition<Integer>> valueList = new ArrayList<>();
        Map<String, String> _map0 = new HashMap<>();
        _map0.put("uk-UA", "НЕАКТИВНИЙ");
        _map0.put("en-US", "Inactive");
        _map0.put("lv-LV", "NEAKTĪVS");
        _map0.put("ms-MY", "Inactive");
        _map0.put("ta-IN", "செயலற்று");
        _map0.put("zh-CN", "Inactive");
        _map0.put("nl-BE", "Inactive");
        _map0.put("kmr-IQ", "INACTIVE");
        _map0.put("ur-PK", "غیر فعال");
        _map0.put("el-GR", "Inactive");
        _map0.put("nl-NL", "Inactive");
        _map0.put("hi-IN", "निष्क्रिय");
        _map0.put("en-AU", "Inactive");
        _map0.put("hy-AM", "Օտարված գույքը");
        _map0.put("he-IL", "לא פעיל");
        _map0.put("mk-MK", "НЕАКТИВЕН");
        _map0.put("ja-JP", "Inactive");
        _map0.put("hu-HU", "INAKTÍV");
        _map0.put("ml-IN", "നിഷ്ക്രിയം");
        _map0.put("ne-NP", "निष्क्रिय");
        _map0.put("ka-GE", "არააქტიური");
        _map0.put("fr-CA", "Inactive");
        _map0.put("fa-IR", "غیرفعال");
        _map0.put("pl-PL", "Nieaktywny");
        _map0.put("pt-PT", "Inactive");
        _map0.put("be-BY", "НЕАКТЫЎНЫ");
        _map0.put("ro-RO", "INACTIV");
        _map0.put("fr-BE", "Inactive");
        _map0.put("ar-EG", "غير نشط");
        _map0.put("ga-IE", "Ná Léi");
        _map0.put("et-EE", "PASSIIVNE");
        _map0.put("tr-TR", "Pasif");
        _map0.put("fr-FR", "Inactive");
        _map0.put("vi-VN", "Inactive");
        _map0.put("en-GB", "Inactive");
        _map0.put("km-KH", "Inactive");
        _map0.put("fi-FI", "PASSIIVINEN");
        _map0.put("nb-NO", "INAKTIV");
        _map0.put("az-AZ", "Fəal deyil");
        _map0.put("hr-HR", "NEAKTIVAN");
        _map0.put("lt-LT", "NEaktyvus");
        _map0.put("gl-ES", "INACTIVO");
        _map0.put("sl-SI", "NEAKTIVNO");
        _map0.put("is-IS", "ÓVIRKUR");
        _map0.put("bg-BG", "НЕАКТИВЕН");
        _map0.put("kn-IN", "ನಿಷ್ಕ್ರಿಯ");
        _map0.put("cs-CZ", "Neaktivní");
        _map0.put("de-DE", "Inactive");
        _map0.put("ca-ES", "INACTIU");
        _map0.put("zh-HK", "Inactive");
        _map0.put("zh-TW", "Inactive");
        _map0.put("ko-KR", "Inactive");
        _map0.put("pt-BR", "Inactive");
        _map0.put("sr-RS", "НЕАКТИВАН");
        _map0.put("sk-SK", "Neaktívne");
        _map0.put("es-ES", "Inactive");
        _map0.put("kk-KZ", "INACTIVE");
        _map0.put("it-IT", "Inactive");
        _map0.put("ru-RU", "Inactive");
        _map0.put("ku-IQ", "ناچالاک");
        _map0.put("bn-BD", "নিষ্ক্রিয়");
        _map0.put("sv-SE", "INAKTIV");
        _map0.put("id-ID", "Inactive");
        _map0.put("da-DK", "INAKTIV");
        _map0.put("mn-MN", "INACTIVE");
        _map0.put("th-TH", "Inactive");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 0, _map0));

        Map<String, String> _map1 = new HashMap<>();
        _map1.put("uk-UA", "У РЕЖИМІ ОЧІКУВАННЯ");
        _map1.put("en-US", "Idle");
        _map1.put("lv-LV", "DIKSTĀVĒ");
        _map1.put("ms-MY", "Idle");
        _map1.put("ta-IN", "செயலற்று");
        _map1.put("zh-CN", "Idle");
        _map1.put("nl-BE", "Idle");
        _map1.put("kmr-IQ", "IDLE");
        _map1.put("ur-PK", "بیکار");
        _map1.put("el-GR", "Idle");
        _map1.put("nl-NL", "Idle");
        _map1.put("hi-IN", "निष्क्रिय");
        _map1.put("en-AU", "Idle");
        _map1.put("hy-AM", "Անգործ");
        _map1.put("he-IL", "סרק");
        _map1.put("mk-MK", "В МИРУВАЊЕ");
        _map1.put("ja-JP", "Idle");
        _map1.put("hu-HU", "TÉTLEN");
        _map1.put("ml-IN", "നിഷ്ക്രിയം");
        _map1.put("ne-NP", "निष्क्रिय");
        _map1.put("ka-GE", "უმოქმედო");
        _map1.put("fr-CA", "Idle");
        _map1.put("fa-IR", "بیکار");
        _map1.put("pl-PL", "TRYB CZASU");
        _map1.put("pt-PT", "Idle");
        _map1.put("be-BY", "У РЭЖЫМЕ ЧАКАННЯ");
        _map1.put("ro-RO", "INACTIV");
        _map1.put("fr-BE", "Idle");
        _map1.put("ar-EG", "خامل");
        _map1.put("ga-IE", "Neamhinneach");
        _map1.put("et-EE", "TÜÜS");
        _map1.put("tr-TR", "Boşta");
        _map1.put("fr-FR", "Idle");
        _map1.put("vi-VN", "Idle");
        _map1.put("en-GB", "Idle");
        _map1.put("km-KH", "Idle");
        _map1.put("fi-FI", "TOIMETON");
        _map1.put("nb-NO", "INAKTIV");
        _map1.put("az-AZ", "İDLE");
        _map1.put("hr-HR", "U MIROVANJU");
        _map1.put("lt-LT", "NEVEIKIA");
        _map1.put("gl-ES", "INACTIVO");
        _map1.put("sl-SI", "V MIROVANJU");
        _map1.put("is-IS", "Í AÐGERÐARLEYSI");
        _map1.put("bg-BG", "НА ПРАЗЕН ХОД");
        _map1.put("kn-IN", "ನಿಷ್ಕ್ರಿಯ");
        _map1.put("cs-CZ", "nezaměřeno");
        _map1.put("de-DE", "Idle");
        _map1.put("ca-ES", "INACTIU");
        _map1.put("zh-HK", "Idle");
        _map1.put("zh-TW", "Idle");
        _map1.put("ko-KR", "Idle");
        _map1.put("pt-BR", "Idle");
        _map1.put("sr-RS", "У МИРОВАЊУ");
        _map1.put("sk-SK", "Stav idle");
        _map1.put("es-ES", "Idle");
        _map1.put("kk-KZ", "IDLE");
        _map1.put("it-IT", "Idle");
        _map1.put("ru-RU", "Idle");
        _map1.put("ku-IQ", "بێکار");
        _map1.put("bn-BD", "নিষ্ক্রিয়");
        _map1.put("sv-SE", "OVERKSAM");
        _map1.put("id-ID", "Idle");
        _map1.put("da-DK", "INAKTIV");
        _map1.put("mn-MN", "IDLE");
        _map1.put("th-TH", "Idle");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 1, _map1));

        Map<String, String> _map2 = new HashMap<>();
        _map2.put("uk-UA", "ОПАЛЕННЯ");
        _map2.put("en-US", "Heating");
        _map2.put("lv-LV", "APKURE");
        _map2.put("ms-MY", "Heating");
        _map2.put("ta-IN", "வெப்பமாக்குகிறது");
        _map2.put("zh-CN", "Heating");
        _map2.put("nl-BE", "Heating");
        _map2.put("kmr-IQ", "HEATING");
        _map2.put("ur-PK", "گرم کر رہا ہے");
        _map2.put("el-GR", "Heating");
        _map2.put("nl-NL", "Heating");
        _map2.put("hi-IN", "गर्म कर रहा है");
        _map2.put("en-AU", "Heating");
        _map2.put("hy-AM", "ՋԵՌՈՒՑՈՒՄ");
        _map2.put("he-IL", "מחמם");
        _map2.put("mk-MK", "ГРЕЕЊЕ");
        _map2.put("ja-JP", "Heating");
        _map2.put("hu-HU", "FŰTÉS");
        _map2.put("ml-IN", "ചൂടാക്കുന്നു");
        _map2.put("ne-NP", "तताउँदै छ");
        _map2.put("ka-GE", "გათბობა");
        _map2.put("fr-CA", "Heating");
        _map2.put("fa-IR", "گرمایش");
        _map2.put("pl-PL", "GRZAJĄCY");
        _map2.put("pt-PT", "Heating");
        _map2.put("be-BY", "АЦЯПЛЕННЕ");
        _map2.put("ro-RO", "ÎNCĂLZEȘTE");
        _map2.put("fr-BE", "Heating");
        _map2.put("ar-EG", "تدفئة");
        _map2.put("ga-IE", "Gréin");
        _map2.put("et-EE", "KÜTAB");
        _map2.put("tr-TR", "Isıtıyor");
        _map2.put("fr-FR", "Heating");
        _map2.put("vi-VN", "Heating");
        _map2.put("en-GB", "Heating");
        _map2.put("km-KH", "Heating");
        _map2.put("fi-FI", "LÄMMITTÄÄ");
        _map2.put("nb-NO", "VARMER");
        _map2.put("az-AZ", "İSTİLİK");
        _map2.put("hr-HR", "GRIJE");
        _map2.put("lt-LT", "ŠILDYMAS");
        _map2.put("gl-ES", "Calentando");
        _map2.put("sl-SI", "OGREVA");
        _map2.put("is-IS", "HITUNARHAMUR");
        _map2.put("bg-BG", "ЗАГРЯВАНЕ");
        _map2.put("kn-IN", "ಬಿಸಿಮಾಡುತ್ತಿದೆ");
        _map2.put("cs-CZ", "vytápívá se");
        _map2.put("de-DE", "Heating");
        _map2.put("ca-ES", "CALEFACCIÓ");
        _map2.put("zh-HK", "Heating");
        _map2.put("zh-TW", "Heating");
        _map2.put("ko-KR", "Heating");
        _map2.put("pt-BR", "Heating");
        _map2.put("sr-RS", "ГРЕЈАЊЕ");
        _map2.put("sk-SK", "Teplé spotrebiťelianie");
        _map2.put("es-ES", "Heating");
        _map2.put("kk-KZ", "HEATING");
        _map2.put("it-IT", "Heating");
        _map2.put("ru-RU", "Heating");
        _map2.put("ku-IQ", "گەرمکردن");
        _map2.put("bn-BD", "গরম করছে");
        _map2.put("sv-SE", "VÄRMER");
        _map2.put("id-ID", "Heating");
        _map2.put("da-DK", "OPVARMER");
        _map2.put("mn-MN", "HEATING");
        _map2.put("th-TH", "Heating");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 2, _map2));

        Map<String, String> _map3 = new HashMap<>();
        _map3.put("uk-UA", "ОХОЛОДЖУВАЛЬНИЙ");
        _map3.put("en-US", "Cooling");
        _map3.put("lv-LV", "DZESĒŠANA");
        _map3.put("ms-MY", "Cooling");
        _map3.put("ta-IN", "குளிரூட்டுகிறது");
        _map3.put("zh-CN", "Cooling");
        _map3.put("nl-BE", "Cooling");
        _map3.put("kmr-IQ", "COOLING");
        _map3.put("ur-PK", "ٹھنڈا کر رہا ہے");
        _map3.put("el-GR", "Cooling");
        _map3.put("nl-NL", "Cooling");
        _map3.put("hi-IN", "ठंडा कर रहा है");
        _map3.put("en-AU", "Cooling");
        _map3.put("hy-AM", "ՍԱՌԵՑՈՒՄ");
        _map3.put("he-IL", "מקרר");
        _map3.put("mk-MK", "ЛАДЕЊЕ");
        _map3.put("ja-JP", "Cooling");
        _map3.put("hu-HU", "HŰTÉS");
        _map3.put("ml-IN", "തണുപ്പിക്കുന്നു");
        _map3.put("ne-NP", "चिसो गर्दैछ");
        _map3.put("ka-GE", "გაგრილება");
        _map3.put("fr-CA", "Cooling");
        _map3.put("fa-IR", "سرمایش");
        _map3.put("pl-PL", "CHŁODZACY");
        _map3.put("pt-PT", "Cooling");
        _map3.put("be-BY", "АХАЛОДЖВАЛЬНЫ");
        _map3.put("ro-RO", "RĂCEȘTE");
        _map3.put("fr-BE", "Cooling");
        _map3.put("ar-EG", "تبريد");
        _map3.put("ga-IE", "Sreabh");
        _map3.put("et-EE", "JAHUTAB");
        _map3.put("tr-TR", "Soğutuyor");
        _map3.put("fr-FR", "Cooling");
        _map3.put("vi-VN", "Cooling");
        _map3.put("en-GB", "Cooling");
        _map3.put("km-KH", "Cooling");
        _map3.put("fi-FI", "JÄÄHDYTTÄÄ");
        _map3.put("nb-NO", "KJØLER");
        _map3.put("az-AZ", "SOYUTMA");
        _map3.put("hr-HR", "HLADI");
        _map3.put("lt-LT", "VĖSINIMAS");
        _map3.put("gl-ES", "Rrefrixionado");
        _map3.put("sl-SI", "HLADI");
        _map3.put("is-IS", "KÆLIR");
        _map3.put("bg-BG", "ОХЛАЖДАНЕ");
        _map3.put("kn-IN", "ತಂಪಾಗಿಸುತ್ತಿದೆ");
        _map3.put("cs-CZ", "chlazení se");
        _map3.put("de-DE", "Cooling");
        _map3.put("ca-ES", "REFREDAMENT");
        _map3.put("zh-HK", "Cooling");
        _map3.put("zh-TW", "Cooling");
        _map3.put("ko-KR", "Cooling");
        _map3.put("pt-BR", "Cooling");
        _map3.put("sr-RS", "ХЛАЂЕЊЕ");
        _map3.put("sk-SK", "Chladné spotrebiťelianie");
        _map3.put("es-ES", "Cooling");
        _map3.put("kk-KZ", "COOLING");
        _map3.put("it-IT", "Cooling");
        _map3.put("ru-RU", "Cooling");
        _map3.put("ku-IQ", "ساردکردنەوە");
        _map3.put("bn-BD", "শীতল করছে");
        _map3.put("sv-SE", "KYLER");
        _map3.put("id-ID", "Cooling");
        _map3.put("da-DK", "KØLER");
        _map3.put("mn-MN", "COOLING");
        _map3.put("th-TH", "Cooling");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 3, _map3));

        super.constraintValue(new ValueList<>(valueList));

    }

}