package cc.openxiot.matrix.device.loach._airconditioner._g1._heatercooler.properties;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

import cn.geekcity.xiot.spec.definition.property.*;
import cn.geekcity.xiot.spec.definition.property.data.DataFormat;
import cn.geekcity.xiot.spec.definition.urn.PropertyType;
import cn.geekcity.xiot.spec.error.IotError;
import cn.geekcity.xiot.support.codegen.vertx.typedef.controller.PropertyController;



/**
 * Property: 目标状态
 */
public class PropertyTargetHeaterCoolerState extends PropertyController<Integer> {

    public static final int IID = 13;
    public static final String TYPE = "urn:homekit-spec:property:target-heater-cooler-state:000000b2:loach:g1:1";

    public PropertyTargetHeaterCoolerState() {
        super(IID, new PropertyType(TYPE), new Access(true, true, true), DataFormat.UINT8);

        super.description().put("zh-CN", "目标状态");

        List<ValueDefinition<Integer>> valueList = new ArrayList<>();
        Map<String, String> _map0 = new HashMap<>();
        _map0.put("uk-UA", "АВТО");
        _map0.put("en-US", "Auto");
        _map0.put("lv-LV", "AUTOMĀTISKI");
        _map0.put("ms-MY", "Auto");
        _map0.put("ta-IN", "தானியங்கி");
        _map0.put("zh-CN", "Auto");
        _map0.put("nl-BE", "Auto");
        _map0.put("kmr-IQ", "AUTO");
        _map0.put("ur-PK", "خودکار");
        _map0.put("el-GR", "Auto");
        _map0.put("nl-NL", "Auto");
        _map0.put("hi-IN", "स्वचालित");
        _map0.put("en-AU", "Auto");
        _map0.put("hy-AM", "Ավտոմեքենա");
        _map0.put("he-IL", "אוטומטי");
        _map0.put("mk-MK", "АВТОМАТСКИ");
        _map0.put("ja-JP", "Auto");
        _map0.put("hu-HU", "AUTOMATIKUS");
        _map0.put("ml-IN", "ഓട്ടോമാറ്റിക്");
        _map0.put("ne-NP", "स्वचालित");
        _map0.put("ka-GE", "ავტო");
        _map0.put("fr-CA", "Auto");
        _map0.put("fa-IR", "خودکار");
        _map0.put("pl-PL", "AUTOMATYCZNY");
        _map0.put("pt-PT", "Auto");
        _map0.put("be-BY", "АЎТА");
        _map0.put("ro-RO", "AUTOMAT");
        _map0.put("fr-BE", "Auto");
        _map0.put("ar-EG", "تلقائي");
        _map0.put("ga-IE", "AIT");
        _map0.put("et-EE", "AUTOMAATNE");
        _map0.put("tr-TR", "Otomatik");
        _map0.put("fr-FR", "Auto");
        _map0.put("vi-VN", "Auto");
        _map0.put("en-GB", "Auto");
        _map0.put("km-KH", "Auto");
        _map0.put("fi-FI", "AUTOMAAATTINEN");
        _map0.put("nb-NO", "AUTO");
        _map0.put("az-AZ", "Automat");
        _map0.put("hr-HR", "AUTOMATSKI");
        _map0.put("lt-LT", "AUTOMATINIS");
        _map0.put("gl-ES", "AUTO");
        _map0.put("sl-SI", "SAMODEJNO");
        _map0.put("is-IS", "SJÁLFVIRKUR");
        _map0.put("bg-BG", "АВТОМАТИЧЕН");
        _map0.put("kn-IN", "ಸ್ವಯಂಚಾಲಿತ");
        _map0.put("cs-CZ", "Automatické");
        _map0.put("de-DE", "Auto");
        _map0.put("ca-ES", "COTXE");
        _map0.put("zh-HK", "Auto");
        _map0.put("zh-TW", "Auto");
        _map0.put("ko-KR", "Auto");
        _map0.put("pt-BR", "Auto");
        _map0.put("sr-RS", "АУТОМАТСКИ");
        _map0.put("sk-SK", "Automatik");
        _map0.put("es-ES", "Auto");
        _map0.put("kk-KZ", "AUTO");
        _map0.put("it-IT", "Auto");
        _map0.put("ru-RU", "Auto");
        _map0.put("ku-IQ", "خۆکار");
        _map0.put("bn-BD", "স্বয়ংক্রিয়");
        _map0.put("sv-SE", "AUTO");
        _map0.put("id-ID", "Auto");
        _map0.put("da-DK", "AUTO");
        _map0.put("mn-MN", "AUTO");
        _map0.put("th-TH", "Auto");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 0, _map0));

        Map<String, String> _map1 = new HashMap<>();
        _map1.put("uk-UA", "ОПАЛЕННЯ");
        _map1.put("en-US", "Heat");
        _map1.put("lv-LV", "APKURE");
        _map1.put("ms-MY", "Heat");
        _map1.put("ta-IN", "வெப்பம்");
        _map1.put("zh-CN", "Heat");
        _map1.put("nl-BE", "Heat");
        _map1.put("kmr-IQ", "HEAT");
        _map1.put("ur-PK", "گرم");
        _map1.put("el-GR", "Heat");
        _map1.put("nl-NL", "Heat");
        _map1.put("hi-IN", "गर्मी");
        _map1.put("en-AU", "Heat");
        _map1.put("hy-AM", "Ջերմաքանակ");
        _map1.put("he-IL", "חום");
        _map1.put("mk-MK", "ГРЕЕЊЕ");
        _map1.put("ja-JP", "Heat");
        _map1.put("hu-HU", "FŰTÉS");
        _map1.put("ml-IN", "ചൂട്");
        _map1.put("ne-NP", "गर्मी");
        _map1.put("ka-GE", "სითბო");
        _map1.put("fr-CA", "Heat");
        _map1.put("fa-IR", "گرما");
        _map1.put("pl-PL", "GRZAJĄCY");
        _map1.put("pt-PT", "Heat");
        _map1.put("be-BY", "АЦЯПЛЕННЕ");
        _map1.put("ro-RO", "ÎNCĂLZIRE");
        _map1.put("fr-BE", "Heat");
        _map1.put("ar-EG", "تدفئة");
        _map1.put("ga-IE", "Gréin");
        _map1.put("et-EE", "KÜTE");
        _map1.put("tr-TR", "Isıt");
        _map1.put("fr-FR", "Heat");
        _map1.put("vi-VN", "Heat");
        _map1.put("en-GB", "Heat");
        _map1.put("km-KH", "Heat");
        _map1.put("fi-FI", "LÄMPÖ");
        _map1.put("nb-NO", "VARME");
        _map1.put("az-AZ", "İstilik");
        _map1.put("hr-HR", "GRIJANJE");
        _map1.put("lt-LT", "ŠILDYMAS");
        _map1.put("gl-ES", "Calentar");
        _map1.put("sl-SI", "OGREVANJE");
        _map1.put("is-IS", "HITI");
        _map1.put("bg-BG", "ОТОПЛЕНИЕ");
        _map1.put("kn-IN", "ಶಾಖ");
        _map1.put("cs-CZ", "vyhřeje");
        _map1.put("de-DE", "Heat");
        _map1.put("ca-ES", "CALOR");
        _map1.put("zh-HK", "Heat");
        _map1.put("zh-TW", "Heat");
        _map1.put("ko-KR", "Heat");
        _map1.put("pt-BR", "Heat");
        _map1.put("sr-RS", "ГРЕЈАЊЕ");
        _map1.put("sk-SK", "Teplé");
        _map1.put("es-ES", "Heat");
        _map1.put("kk-KZ", "HEAT");
        _map1.put("it-IT", "Heat");
        _map1.put("ru-RU", "Heat");
        _map1.put("ku-IQ", "گەرمی");
        _map1.put("bn-BD", "তাপ");
        _map1.put("sv-SE", "VÄRME");
        _map1.put("id-ID", "Heat");
        _map1.put("da-DK", "VARME");
        _map1.put("mn-MN", "HEAT");
        _map1.put("th-TH", "Heat");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 1, _map1));

        Map<String, String> _map2 = new HashMap<>();
        _map2.put("uk-UA", "ОХОЛОДЖЕННЯ");
        _map2.put("en-US", "Cool");
        _map2.put("lv-LV", "DZESĒŠANA");
        _map2.put("ms-MY", "Cool");
        _map2.put("ta-IN", "குளிர்");
        _map2.put("zh-CN", "Cool");
        _map2.put("nl-BE", "Cool");
        _map2.put("kmr-IQ", "COOL");
        _map2.put("ur-PK", "ٹھنڈا");
        _map2.put("el-GR", "Cool");
        _map2.put("nl-NL", "Cool");
        _map2.put("hi-IN", "ठंडा");
        _map2.put("en-AU", "Cool");
        _map2.put("hy-AM", "Հերիք է ։");
        _map2.put("he-IL", "קרור");
        _map2.put("mk-MK", "ЛАДЕЊЕ");
        _map2.put("ja-JP", "Cool");
        _map2.put("hu-HU", "HŰTÉS");
        _map2.put("ml-IN", "തണുപ്പ്");
        _map2.put("ne-NP", "चिसो");
        _map2.put("ka-GE", "გრილი");
        _map2.put("fr-CA", "Cool");
        _map2.put("fa-IR", "سرما");
        _map2.put("pl-PL", "CHŁODZACY");
        _map2.put("pt-PT", "Cool");
        _map2.put("be-BY", "АХАЛОДЖВАННЕ");
        _map2.put("ro-RO", "RĂCIRE");
        _map2.put("fr-BE", "Cool");
        _map2.put("ar-EG", "تبريد");
        _map2.put("ga-IE", "Sreabh");
        _map2.put("et-EE", "JAHUTUS");
        _map2.put("tr-TR", "Soğut");
        _map2.put("fr-FR", "Cool");
        _map2.put("vi-VN", "Cool");
        _map2.put("en-GB", "Cool");
        _map2.put("km-KH", "Cool");
        _map2.put("fi-FI", "VILEÄ");
        _map2.put("nb-NO", "KJØL");
        _map2.put("az-AZ", "Ə'la");
        _map2.put("hr-HR", "HLAĐENJE");
        _map2.put("lt-LT", "VĖSINIMAS");
        _map2.put("gl-ES", "Refreiar");
        _map2.put("sl-SI", "HLAJENJE");
        _map2.put("is-IS", "KULD");
        _map2.put("bg-BG", "ОХЛАЖДАНЕ");
        _map2.put("kn-IN", "ತಂಪು");
        _map2.put("cs-CZ", "chladne");
        _map2.put("de-DE", "Cool");
        _map2.put("ca-ES", "GENIAL");
        _map2.put("zh-HK", "Cool");
        _map2.put("zh-TW", "Cool");
        _map2.put("ko-KR", "Cool");
        _map2.put("pt-BR", "Cool");
        _map2.put("sr-RS", "ХЛАЂЕЊЕ");
        _map2.put("sk-SK", "Chladné");
        _map2.put("es-ES", "Cool");
        _map2.put("kk-KZ", "COOL");
        _map2.put("it-IT", "Cool");
        _map2.put("ru-RU", "Cool");
        _map2.put("ku-IQ", "سارد");
        _map2.put("bn-BD", "শীতল");
        _map2.put("sv-SE", "KYLA");
        _map2.put("id-ID", "Cool");
        _map2.put("da-DK", "KØL");
        _map2.put("mn-MN", "COOL");
        _map2.put("th-TH", "Cool");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 2, _map2));

        Map<String, String> _map3 = new HashMap<>();
        _map3.put("uk-UA", "ВИМК");
        _map3.put("en-US", "Off");
        _map3.put("lv-LV", "IZSLĒGTS");
        _map3.put("ms-MY", "Off");
        _map3.put("ta-IN", "அணைக்க");
        _map3.put("zh-CN", "Off");
        _map3.put("nl-BE", "Off");
        _map3.put("kmr-IQ", "OFF");
        _map3.put("ur-PK", "بند");
        _map3.put("el-GR", "Off");
        _map3.put("nl-NL", "Off");
        _map3.put("hi-IN", "बंद");
        _map3.put("en-AU", "Off");
        _map3.put("hy-AM", "Անջատել");
        _map3.put("he-IL", "כבוי");
        _map3.put("mk-MK", "ИСКЛУЧЕН");
        _map3.put("ja-JP", "Off");
        _map3.put("hu-HU", "KI");
        _map3.put("ml-IN", "ഓഫ്");
        _map3.put("ne-NP", "बन्द");
        _map3.put("ka-GE", "გამორთული");
        _map3.put("fr-CA", "Off");
        _map3.put("fa-IR", "خاموش");
        _map3.put("pl-PL", "WYŁĄCZONY");
        _map3.put("pt-PT", "Off");
        _map3.put("be-BY", "ВЫКЛ");
        _map3.put("ro-RO", "OPRIT");
        _map3.put("fr-BE", "Off");
        _map3.put("ar-EG", "إيقاف");
        _map3.put("ga-IE", "Neamhinneach");
        _map3.put("et-EE", "VÄLJAS");
        _map3.put("tr-TR", "Kapalı");
        _map3.put("fr-FR", "Off");
        _map3.put("vi-VN", "Off");
        _map3.put("en-GB", "Off");
        _map3.put("km-KH", "Off");
        _map3.put("fi-FI", "POIS PÄÄLTÄ");
        _map3.put("nb-NO", "AV");
        _map3.put("az-AZ", "getmək");
        _map3.put("hr-HR", "ISKLJUČENO");
        _map3.put("lt-LT", "IŠJUNGTA");
        _map3.put("gl-ES", "Parado");
        _map3.put("sl-SI", "IZKLOPLJENO");
        _map3.put("is-IS", "SLÖKKT");
        _map3.put("bg-BG", "ИЗКЛЮЧЕН");
        _map3.put("kn-IN", "ಆಫ್");
        _map3.put("cs-CZ", "vypnuto");
        _map3.put("de-DE", "Off");
        _map3.put("ca-ES", "APAGAT");
        _map3.put("zh-HK", "Off");
        _map3.put("zh-TW", "Off");
        _map3.put("ko-KR", "Off");
        _map3.put("pt-BR", "Off");
        _map3.put("sr-RS", "ИСКЉУЧЕНО");
        _map3.put("sk-SK", "Vypnutý");
        _map3.put("es-ES", "Off");
        _map3.put("kk-KZ", "OFF");
        _map3.put("it-IT", "Off");
        _map3.put("ru-RU", "Off");
        _map3.put("ku-IQ", "کوژاوە");
        _map3.put("bn-BD", "বন্ধ");
        _map3.put("sv-SE", "AV");
        _map3.put("id-ID", "Off");
        _map3.put("da-DK", "SLUKKET");
        _map3.put("mn-MN", "OFF");
        _map3.put("th-TH", "Off");
        valueList.add(new ValueDefinition<>(DataFormat.UINT8, 3, _map3));

        super.constraintValue(new ValueList<>(valueList));

    }

}